version: '3'

networks:
  app-tier:
    driver: bridge

services:

  jupyter:
    build:
      context: . 
      dockerfile: docs/Dockerfile
    volumes:
      - ./docs:/docs:z
      - ./:/app:z
    ports:
      - "8889:8888"
    working_dir: "/docs"
    networks:
      - app-tier
    command: |
      bash -c "jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root"

  jupyter-book:
    build:
      context: . 
      dockerfile: docs/Dockerfile
    volumes:
      - ./docs:/docs:z
      - ./:/app:z
    ports:
      - "8001:8001"
    networks:
      - app-tier
    working_dir: "/docs"
    command: |
      bash -c "python /docs/run_jupyterbook.py"
